# -*- coding: utf-8 -*-
"""Patterns Assignment-4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17h2TxFoESlCP_2vGAxPRREreu_d6wwvC

**Algorithms**
"""

# 1 Confirm whether given number is a 3 digit number? 
a =input('Enter a number: ')
if ((len(a)==3) and a.isnumeric()):
  print('3 digit number')
else:
  print('no. is not a 3 digit')

#  2. Confirm whether given number is an 'N' digit number? 
# (Input should not be string)
a = int(input('enter a number: '))
b = str(a)
c = len(b)
print(f'it is a {c} digit number')

# 3 Find whether a given number is a prime number or not? 
num = int(input("Enter a number: "))
if num > 1:
   for i in range(2,num):
       if (num % i) == 0:
           print(num,"is not a prime number")
           break
   else:
       print(num,"is a prime number")
else:
   print(num,"neither prime or composite number")

# 4  Write a program to compute the distance between the points (x1, y1) and (x2, y2)? 
a = int(input('enter x1: '))
b = int(input('enter x2: '))
c = int(input('enter y1: '))
d = int(input('enter y2: '))
k = ((((b-a)**2)+((d-c)**2))**0.5)
print(k)

# 5  Write a program to calculate body mass index? 
a = float(input('enter mass of body: '))
b = float(input('enter height of body: '))
bmi = a/(b*b)
print('body mass index',bmi)

# 6  Write a program to filter the positive numbers from a list?
a = [2,-3,5,-1]
for i in a:
    if i >= 0:
       print(i, end = " ")

# 7  Write a program to test whether a passed letter is a vowel or not?
a = input('enter any letter: ')
b = ['a','e','i','o','u','A','E','I','O','U']
if a in b:
  print('ita a vowel')
else:
  print('not a vowel')

# 8. WAP to Check whether given year is a leap year or not?
a=int(input('enter a year'))
if ((a%4)==0) and ((a%100)!=0) :
  print('its a leap year')
# elif ((a%100)==0):
  # print('leap year')
elif ((a%400)==0) :
  print('it is a leap year')
else:
  print('not a leap year')

# 9. WAP to check whether given string is a palindrome or not?
  #  // EX: MADAM //Palindrome
          #  ANT  // Not a palindrome
a =input('enter a string:')
if (a[::-1]==a):
  print('is a palindromic')
elif (a[::-1]!=a):
   print('not a palindromic string')

# 10. WAP to delete all the positive numbers from the arr
  #  //Note : Do not create separate list, Remove the positive elements from the existing array.
  #  // Ex: input: [2,-1,-5.6,4,89,43,-35,09]
          # output: [-1,-5.6,-35]
a=[2,-1,-5.6,4,89,43,-35,9] # if we are giving '09' in input  its showing error as invalid token.
for i in a:
  if i<0:
    print(i,end=" ")

# 11. WAP to remove duplicates from the given list?
  #  // Ex: input: [2,21,-5.6,21,89,43,-5,09,2,34,43]
          # output:  [2,21,-5.6,89,34,-5,09,43]
list=[2,21,-5.6,21,89,43,-5,9,2,34,43]
result=[]
for i in list:
  if i not in result:
    result.append(i)
print(result)

"""**Patterns**

"""

#1
#Patterns.[using for and while loop]
# * * * * *
# * * * *
# * * * 
# * *
# *
# for i in range(5,0,-1):
#   print('* '*i)

i=1                  # using while loop
a=6
while i in range(1,a):
  print('* '*(a-i))
  i+=1

#1.
#Patterns.[using function in for and while loop]
# * * * * *
# * * * *
# * * * 
# * *
# *
# def vat(n):    
#   for i in range(n,0,-1):
#      print('* '*i)

# vat(n=int(input('enter no. of rows: ')))


def vat(n):
  i=1             
  a=6

  while i in range(1,a):
    print('* '*(a-i))
    i+=1
vat(n=int(input('enter no. of rows: ')))

#2.
    # * [using for and while loop]]
  #  **
  # ***
#  ****
# *****    
# a = int(input('enter the rows : '))
# for i in  range(1,a+1):
#   print((a-i) * ' '+ i * '*')


a = int(input('enter the rows : '))
i=1
while i in range(1,a+1):
  print((a-i) * ' '+ i * '*')
  i+=1

#2.
    # * [using function in for and while loop]]
  #  **
  # ***
#  ****
# *****    
# def gg(n):
#   for i in  range(1,a+1):
#     print((a-i) * ' '+ i * '*')
# gg(n=int(input('enter no. of rows: ')))


def gg(n):
  i=1
  while i in range(1,n+1):
    print((n-i) * ' '+ i * '*')
    i+=1
gg(5)

#3.
    # *     [using for and while loop]
  #  ***
  # *****
#  *******
# *********

# star=10 
# space=5
# for i in range(1,star,2):     
#   print((' '*space)+('*'*i))
#   space=space-1


a = 1
b = int(input('enter no. of rows: '))      
i = 1
while i in range(1,b+1):
  print(((b-i)*' ')+('*'*a)+((b-i)*' '))
  a = a+2
  i+=1

#3.
    # *     [using function in  for and while loop]
  #  ***
  # *****
#  *******
# *********

# def jo(n,m):  
#   for i in range(1,n,2):
#     print((' '*m)+('*'*i))
#     m=m-1
# jo(n=int(input('enter n value (no.of stars): ')),m=int(input('enter m value (space): ')))


def jo(n,m):   
  i = 1
  while i in range(1,m+1):
     print(((m-i)*' ')+('*'*n)+((m-i)*' '))
     n = n+2
     i+=1

jo(1,m=int(input('enter m value (space): ')))

#4. 
# *********    [using for and while loop]
#  ******* 
  # *****  
  #  ***   
    # *
# star =9
# space=1
# for i in range(star,0,-2):           
#   print((' '*space)+('*'*i))
#   space=space+1


a=9
b=9
i=1
while i in range(0,a+2):
  print((i*' ')+(b*'*'))
  b=b-2
  i+=1

#4.
# *********    [using function in  for and while loop]
#  ******* 
  # *****  
  #  ***   
    # *

def hh(n,m):   
  for i in range(n,0,-2):
    print((' '*m)+('*'*i))
    m=m+1
hh(n=int(input('enter n value (stars): ')),m=int(input('enter m value (space): ')))


# def hh(n,m):
#   i=1
# while i in range(0,n+2):         incorrect code
#   print((i*' ')+(m*'*'))
#   m=m-2
#   i+=1

# hh(9,5)

#5.   
# 1   [using for and while loop]
# 11
# 111
# 1111
# 11111
# a = int(input('enter no. of rows: '))
# i=1
# for i in range(1,a+1):
#   print('1'*i)


a = int(input('enter no. of rows: '))
i=1
while i in range(1,a+1):
  print('1'*i)
  i+=1

#5. 
# 1   [using function in for and while loop]
# 11
# 111
# 1111
# 11111
# def hh(n,m):
#   i=1
#   for i in range(1,a+i):
#     print('1'*i)
#     i+=1
# hh(0,0)

def jj(n):
  i=1
  while i in range(1,a+1):
    print('1'*i)
    i+=1
jj(n=int(input('enter no. of rows: ')))

#6.
# 1    [using for loop]
# 12
# 123 
# 1234
# 12345
# 123456
# 1234567
# 12345678
a=0
for i in range(1,10):
  a=a+1
  v=' '
for j in range(1,a):
  v=v+str(j)
  print(v)

#6.
# 1    [using function in for loop]
# 12
# 123 
# 1234
# 12345
# 123456
# 1234567
# 12345678
def ho(n):   
  for i in range(n):
    for j in range(i+1):
      print(j+1,end='')
    print(' ')
ho(n = int(input('enter no of rows: ')))

#7.
# 2  9
# 3  8
# 4  7
# 5  6
# 6  5
# 7  4
# 8  3
# 9  2
# 10 1

for i in range(2,11):
  print(i,11-i)

#8.
# 0 * 9 + 8        = 8
# 9 * 9 + 7        = 88
# 98 * 9 + 6       = 888
# 987 * 9 + 5      = 8888
# 9876 * 9 + 4     = 88888
# 98765 * 9 + 3    = 888888
# 987654 * 9 + 2   = 8888888
# 9876543 * 9 + 1  = 88888888
# 98765432 * 9 + 0 = 888888888
a='098765432'
sum=" "
n=9
for i in range(0,9):
  sum = sum +a[i]
  b=int(sum)
  n=n-1
  print(b,'x','9','+',n,'=',(b*9)+n)

#9.
# 1
# 22
# 333
# 4444
# 55555       #[using for and while loop]
a = int(input('enter no. of rows: '))
i = 1
j = 0
# while i in range(1,a+1):
#   b=j+1
#   c=str(b)
#   print(c*i)
#   i=i+1
#   j=j+1


for i in range(1,a+1):
  b=j+1
  c=str(b)
  print(c*i)
  i=i+1
  j=j+1

#10.
# 54321
# 4321
# 321
# 21
# 1
a= 7
for i in range(1,6):
  a=a-1
  c=''
  for j in range(1,a):
    c=c+str(j)
    d=c[::-1]
  print(d)

#11.
# 1 
# 2  3
# 4  5  6
# 7  8  9  10
# 11 12 13 14 15
b = 1
for i in range(0,5):
    for j in range(i+1):
      if b>9:
        print(b,end=' ')
      else:
        print(b, end="  ")
      b = b+1
    print()

#12.
# 1  2  3  4  5
# 6  7  8  9
# 10 11 12
# 13 14
# 15

b = 1
for i in range(6,0,-1):
    for j in range(i-1):
      if b>9:
        print(b,end=' ')
      else:
        print(b, end="  ")
      b = b+1
    print()

#13.(using for loop)
# 1
# 2 4
# 3 6 9
# 4 8 12 16
# 5 10 15 20 25
# 6 12 18 24 30 36
# 7 14 21 28 35 42 49
# 8 16 24 32 40 48 56 64
# 9 18 27 36 45 54 63 72 81
# 10 20 30 40 50 60 70 80 90 100
a= int(input('enter the number of rows: '))
for i in range(1, a + 1):
    for j in range(1, i + 1):
        print(i * j, end=' ')
    print('')

#14.
#             1  
#          2  3  
#       4  5  6  
#    7  8  9  10 
# 11 12 13 14 15 

k=1
l=12
for i in range(1,6):
  print(l*' ',end='')
  for j in range(i):
    s=' '
    if k>9:
      l=0
      print(k,end=' ')
    else:
      print(k,end='  ')
    k=k+1
  print()
  l-=3

#15.
# A    [using for and while loop]
# AB
# ABC
# ABCD
# ABCDE
# a = ['A','B','C','D','E']
# b = ''
# for i in range(0,5):
#   b+=a[i]
#   print(b)

a = ['A','B','C','D','E']
b=''
i=0
while i in range(0,5):
  b+=a[i]
  print(b)
  i+=1

# 15.
# A    [using function in  for and while loop]
# AB
# ABC
# ABCD
# ABCDE
# def gg(a):
#   a = ['A','B','C','D','E']
#   b=''
#   i=0
#   while i in range(0,5):
#     b+=a[i]
#     print(b)
#     i+=1

# gg(a)


def gg(a):
  a = ['A','B','C','D','E']
  b = ''
  for i in range(0,5):
    b+=a[i]
    print(b)

gg(a)

#16.
#   A
#  ABC
# ABCDE
n = 3 
for i in range(n):
    for j in range(n - i):
        print(' ', end='')
    for k in range(2 * i + 1):
        print(chr(65 + k), end='')
    print()

#17.
# A  [using for and while loop]
# A A 
# A A A 
# A A A A 
# A A A A A
a = int(input('enter the rows: '))
# for i in range(1,a+1):
#   print(i * ' A' + i * ' ')

i=1
while i in range(1,a+1):
  print(i*'A '+i*' ')
  i+=1

#17.
# A  [using function in for and while loop]
# A A 
# A A A 
# A A A A 
# A A A A A
# def ff(n):
#   for i in range(1,n+1):
#     print(i * ' A' + i * ' ')

# ff(n=int(input('enter  a number of rows: ')))

def ff(n):
  i=1
  while i in range(1,n+1):
    print(i*'A '+i*' ')
    i+=1

ff(n=int(input('enter  a number of rows: ')))